podTemplate(label: 'mypod', containers: [
    containerTemplate(name: 'docker', image: 'docker', ttyEnabled: true, command: 'cat'),
  ],
  volumes: [
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
  ]) {
    node('mypod') {

        stage('docker pull') {
            container('docker') {
                    sh """
                        docker pull ubuntu
                        """
            }
        }

        stage('docker tag') {
            container('docker') {
                    sh """
                        docker tag ubuntu ubuntu:${env.BUILD_NUMBER}
                        """
            }
        }

        stage('docker run') {
            container('docker') {
                    sh """
                        docker run ubuntu:${env.BUILD_NUMBER} echo Hello Ubuntu
                    """
            }
        }
    }
}

