apiVersion: apps/v1beta1  
kind: Deployment
metadata:
  name: nexus3
  namespace: dev  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      containers:
      - name: nexus3
        image: sonatype/nexus3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081

