apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    filebeat.registry_file: /var/log/containers/filebeat_registry

    filebeat.prospectors:
    - input_type: log
      paths:
        - "/var/log/containers/*.log"
      exclude_files: ['filebeat.*log','kube.*log']
      symlinks: true
      json.message_key: log
      json.keys_under_root: true
      json.add_error_key: true
      multiline.pattern: '^\s'
      multiline.match: after
      document_type: kube-logs

    output.logstash:
        hosts: ["logstash:5044"]
        timeout: 15

    # Sets log level. The default log level is info.
    # Available log levels are: critical, error, warning, info, debug
    logging.level: info

