kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logbackups
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: gluster-cluster
  selector:
    matchLabels:
      storage: "appdata7"