apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    component: logstash
spec:
  selector:
    name: logstash
  ports:
  - name: beats
    port: 5044
    protocol: TCP
    targetPort: 5044
  type: NodePort