apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |-
    # Input section
    input {
      beats {
        port => 5044
      }
    }
    # Filter section

    # Output section
    output {
      elasticsearch { hosts => ["elasticsearch:9200"] }
      file { path => "/usr/share/logstash/logbackups/%{+yyyy.MM.dd}/${HOSTNAME}/logstash_%{type}.log"}
      # file { path => "/tmp/test.out" }
      # stdout { codec => rubydebug }
    }  
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false
  timezone: |-
    Australia/Sydney