apiVersion: v1
kind: Service
metadata:
  name: mysqlicare
  labels:
    app: "mysqlicare"
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: "mysqlicare"
